import { v4 as uuid } from "uuid";

/**
 * Product Database can be added here.
 * You can add products of your wish with different attributes
 * */

export const products = [
  {
    _id: uuid(),
    image: "https://example.com/product1.jpg",
    category: "Women",
    rating: "4.5",
    description: "Womens Floral Print Maxi Dress",
    title: "Elegant Blossoms",
    trending: true,
    original_price: "1499",
    price: "999",
    reviews: "1.2k",
    in_stock: true,
  },
  {
    _id: uuid(),
    image: "https://example.com/product2.jpg",
    category: "Men",
    rating: "4.2",
    description: "Mens Slim Fit Denim Jeans",
    title: "Urban Denim",
    trending: true,
    original_price: "1299",
    price: "899",
    reviews: "987",
    in_stock: true,
  },
  {
    _id: uuid(),
    image: "https://example.com/product3.jpg",
    category: "Kids",
    rating: "4.7",
    description: "Kids' Cartoon Print T-shirt",
    title: "Playful Prints",
    trending: false,
    original_price: "699",
    price: "499",
    reviews: "562",
    in_stock: true,
  },
  {
    _id: uuid(),
    image: "https://example.com/product4.jpg",
    category: "Men",
    rating: "4.0",
    description: "Men's Classic Oxford Shirt",
    title: "Classic Oxford",
    trending: false,
    original_price: "899",
    price: "699",
    reviews: "678",
    in_stock: true,
  },
  {
    _id: uuid(),
    image: "https://example.com/product5.jpg",
    category: "Women",
    rating: "4.3",
    description: "Women's High-Waisted Skinny Jeans",
    title: "Sleek Fit",
    trending: true,
    original_price: "1399",
    price: "1099",
    reviews: "1.8k",
    in_stock: true,
  },

  {
    _id: uuid(),
    image: "https://example.com/product6.jpg",
    category: "Men",
    rating: "4.8",
    description: "Men's Casual Polo Shirt",
    title: "Polo Classic",
    trending: true,
    original_price: "999",
    price: "799",
    reviews: "1.6k",
    in_stock: true,
  },

  {
    _id: uuid(),
    image: "https://example.com/product7.jpg",
    category: "Kids",
    rating: "4.6",
    description: "Kids' Denim Overall Dress",
    title: "Denim Dream",
    trending: false,
    original_price: "899",
    price: "699",
    reviews: "412",
    in_stock: true,
  },

  {
    _id: uuid(),
    image: "https://example.com/product8.jpg",
    category: "Women",
    rating: "4.2",
    description: "Women's V-Neck Floral Blouse",
    title: "Floral Finesse",
    trending: true,
    original_price: "1099",
    price: "899",
    reviews: "875",
    in_stock: true,
  },

  {
    _id: uuid(),
    image: "https://example.com/product9.jpg",
    category: "Men",
    rating: "4.5",
    description: "Men's Casual Cargo Shorts",
    title: "Cargo Comfort",
    trending: false,
    original_price: "799",
    price: "599",
    reviews: "1.2k",
    in_stock: true,
  },

  {
    _id: uuid(),
    image: "https://example.com/product10.jpg",
    category: "Women",
    rating: "4.4",
    description: "Women's Striped Cotton Shirt",
    title: "Striped Delight",
    trending: true,
    original_price: "899",
    price: "699",
    reviews: "958",
    in_stock: true,
  },

  {
    _id: uuid(),
    image: "https://example.com/product11.jpg",
    category: "Kids",
    rating: "4.7",
    description: "Kids' Hooded Sweatshirt",
    title: "Cozy Comfort",
    trending: false,
    original_price: "599",
    price: "399",
    reviews: "326",
    in_stock: true,
  },

  {
    _id: uuid(),
    image: "https://example.com/product12.jpg",
    category: "Men",
    rating: "4.1",
    description: "Men's Checked Formal Shirt",
    title: "Classic Checks",
    trending: false,
    original_price: "999",
    price: "799",
    reviews: "562",
    in_stock: true,
  },

  {
    _id: uuid(),
    image: "https://example.com/product13.jpg",
    category: "Women",
    rating: "4.6",
    description: "Women's Floral Print Skater Dress",
    title: "Floral Fling",
    trending: true,
    original_price: "1499",
    price: "1199",
    reviews: "1.4k",
    in_stock: true,
  },

  {
    _id: uuid(),
    image: "https://example.com/product14.jpg",
    category: "Kids",
    rating: "4.3",
    description: "Kids' Printed Trousers",
    title: "Printed Play",
    trending: false,
    original_price: "699",
    price: "499",
    reviews: "786",
    in_stock: true,
  },

  {
    _id: uuid(),
    image: "https://example.com/product15.jpg",
    category: "Men",
    rating: "4.9",
    description: "Men's Sports Performance T-shirt",
    title: "Active Sportswear",
    trending: true,
    original_price: "799",
    price: "599",
    reviews: "2.3k",
    in_stock: true,
  },

  {
    _id: uuid(),
    image: "https://example.com/product16.jpg",
    category: "Women",
    rating: "4.2",
    description: "Women's Cropped Denim Jacket",
    title: "Denim Chic",
    trending: false,
    original_price: "1099",
    price: "899",
    reviews: "765",
    in_stock: true,
  },

  {
    _id: uuid(),
    image: "https://example.com/product17.jpg",
    category: "Kids",
    rating: "4.5",
    description: "Kids' Striped Polo Shirt",
    title: "Striped Style",
    trending: false,
    original_price: "799",
    price: "599",
    reviews: "862",
    in_stock: true,
  },

  {
    _id: uuid(),
    image: "https://example.com/product18.jpg",
    category: "Men",
    rating: "4.3",
    description: "Men's Hooded Sweatshirt",
    title: "Casual Comfort",
    trending: true,
    original_price: "1199",
    price: "999",
    reviews: "1.9k",
    in_stock: true,
  },

  {
    _id: uuid(),
    image: "https://example.com/product19.jpg",
    category: "Women",
    rating: "4.7",
    description: "Women's High-Waisted Culottes",
    title: "Culotte Bliss",
    trending: true,
    original_price: "1299",
    price: "1099",
    reviews: "1.3k",
    in_stock: true,
  },
  {
    _id: uuid(),
    image: "https://example.com/product20.jpg",
    category: "Kids",
    rating: "4.4",
    description: "Kids' Printed Hoodie",
    title: "Printed Fun",
    trending: false,
    original_price: "899",
    price: "699",
    reviews: "521",
    in_stock: true,
  },
];
